-- Adicionar colunas SAFECHECK-specific à tabela users
ALTER TABLE users ADD COLUMN IF NOT EXISTS matricula VARCHAR(50) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS setor VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gestorImediato VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS senhaDigitos VARCHAR(4);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT true NOT NULL;
